import Head from 'next/head'
import Header from "../components/Header";
import Nav from "../components/Nav"
import requests from '../utils/requests';
import Results from '../components/Results';

export default function Home(props) {
  console.log(props)
  return (
    <div >
      <Head>
        <title>Hulu 2</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header/>

      <Nav/>
      {/*Results*/}
      <Results/>
    </div> 
  );
}


export async function getServerSideProps(context){
  const genre = context.query.genre;

  const requests = await fetch(
  `https://api.themoviedb.org/3/movie${requests[genre]?.url}`
    ).then((res) => res.json());

    return {
        props:{
          results:requests.results,
        },
      }
} 
